<nav class="menu">
	<ul>
		<li <?php if ($thisPage == 'index') {echo 'class = "is-current"';} ?>><a href="index.php">Team Vancouver</a></li>
		<li <?php if ($thisPage == 'lingling') {echo 'class = "is-current"';} ?>><a href="lingling.php">Lingling</a></li>
		<li <?php if ($thisPage == 'valerie') {echo 'class = "is-current"';} ?>><a href="valerie.php">Valerie</a></li>
		<li <?php if ($thisPage == 'kevin') {echo 'class = "is-current"';} ?>><a href="kevin.php">Kevin</a></li>
	</ul>
</nav>
